#!/usr/bin/env python

import sys
import json
import os


# Make no changes to the task, simply observe.
old = json.loads(sys.stdin.readline())
new = json.loads(sys.stdin.readline())
print(json.dumps(new))

if 'intheamtrellolistname' in new:
    if 'start' in new and not 'start' in old:
        print("move to doing")

    elif not 'start' in new and 'start' in old:
        print("move to backlog")
